flag = "SEVIRUhFSEFXCg=="
idk = "nice_try"
hint = "The flag is base64 encoded. Try decoding it to get the flag."
elite = "nice_"
barbarian = "try"
clone = "not_so_fast"
rage = "you_will_never_get_the_flag"
flag1 = "apple"
flag2 = "R3d1snot5u5"